-- ============================================================================
-- Nexo Criminal - Esquema de base de datos (01-schema.sql)
-- ============================================================================
-- Recrea la estructura COMPLETA desde cero sobre una base vacia.
--
-- USO:
--   psql "URL_DE_LA_BASE" -f database/01-schema.sql
--   psql "URL_DE_LA_BASE" -f database/02-datos-ejemplo.sql
--
-- Orden interno (respeta dependencias):
--   1. Extension PostGIS
--   2. Funcion del trigger de geometria
--   3. Tablas (la columna geom se define aqui, NO se agrega despues)
--   4. Claves foraneas
--   5. Indices
--   6. Trigger de geometria
--   7. Vista del grafo
--
-- Nota: la columna geom de 'ubicacion' se define directamente en el CREATE TABLE.
-- Esto evita el error "record new has no field geom" que ocurre cuando la tabla
-- se crea sin esa columna (por ejemplo si Hibernate la crea antes).
-- ============================================================================

-- ============================================================================
-- 1. EXTENSION POSTGIS (imprescindible para la columna geom)
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================================================
-- 2. FUNCION DEL TRIGGER: calcula geom a partir de latitud/longitud
-- ============================================================================
CREATE OR REPLACE FUNCTION trigger_ubicacion_set_geom() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.geom := ST_SetSRID(ST_MakePoint(NEW.longitud, NEW.latitud), 4326)::geography;
    RETURN NEW;
END;
$$;

-- ============================================================================
-- 3. TABLAS
-- ============================================================================

-- --- usuario ---------------------------------------------------------------
CREATE TABLE usuario (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo          boolean,
    creado_en       timestamp(6) without time zone,
    nombre_completo character varying(150),
    password_hash   character varying(255) NOT NULL,
    rol             character varying(20),
    username        character varying(50)  NOT NULL,
    CONSTRAINT uk_usuario_username UNIQUE (username)
);

-- --- persona ---------------------------------------------------------------
CREATE TABLE persona (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actualizado_en   timestamp(6) without time zone,
    alias            character varying(100),
    apellido         character varying(100) NOT NULL,
    creado_en        timestamp(6) without time zone,
    documento        character varying(20)  NOT NULL,
    estado           character varying(20),
    fecha_nacimiento date,
    nombre           character varying(100) NOT NULL,
    rol              character varying(20)  NOT NULL,
    telefono         character varying(20),
    CONSTRAINT uk_persona_documento UNIQUE (documento),
    CONSTRAINT persona_rol_check CHECK (
        (rol)::text = ANY (ARRAY[
            'VICTIMA','SOSPECHOSO','TESTIGO','PROPIETARIO','INTERMEDIARIO'
        ]::text[])
    )
);

-- --- ubicacion (con geom incluida desde el inicio) -------------------------
CREATE TABLE ubicacion (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_en       timestamp(6) without time zone,
    direccion       character varying(255),
    latitud         double precision NOT NULL,
    longitud        double precision NOT NULL,
    nodo_sospechoso boolean,
    tipo            character varying(30),
    geom            geography(Point,4326),
    CONSTRAINT ubicacion_tipo_check CHECK (
        (tipo)::text = ANY (ARRAY[
            'TALLER','GALPON','TERRENO_BALDIO','DOMICILIO','CAJERO',
            'TRANSPORTE_PUBLICO','COMERCIO','OTRO'
        ]::text[])
    )
);

-- --- vehiculo --------------------------------------------------------------
CREATE TABLE vehiculo (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio           integer,
    chasis         character varying(40),
    color          character varying(40),
    creado_en      timestamp(6) without time zone,
    declaracion    text,
    estado         character varying(30) NOT NULL,
    marca          character varying(80) NOT NULL,
    modelo         character varying(80) NOT NULL,
    placa          character varying(20) NOT NULL,
    propietario_id bigint,
    CONSTRAINT uk_vehiculo_placa UNIQUE (placa),
    CONSTRAINT vehiculo_estado_check CHECK (
        (estado)::text = ANY (ARRAY[
            'NORMAL','ROBADO','RECUPERADO','DESAPARECIDO',
            'BAJO_OBSERVACION','VEHICULO_APOYO'
        ]::text[])
    )
);

-- --- suceso ----------------------------------------------------------------
CREATE TABLE suceso (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_en           timestamp(6) without time zone,
    descripcion         text,
    fecha_hora          timestamp(6) without time zone NOT NULL,
    modus_operandi      character varying(100),
    tipo                character varying(30) NOT NULL,
    ubicacion_id        bigint,
    ubicacion_ultima_id bigint,
    vehiculo_id         bigint,
    victima_id          bigint,
    CONSTRAINT suceso_tipo_check CHECK (
        (tipo)::text = ANY (ARRAY[
            'ROBO_VEHICULO','DESAPARICION','AVISTAMIENTO','TRANSACCION'
        ]::text[])
    )
);

-- --- relacion --------------------------------------------------------------
CREATE TABLE relacion (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_en      timestamp(6) without time zone,
    peso           integer,
    tipo_relacion  character varying(30) NOT NULL,
    persona_a_id   bigint NOT NULL,
    persona_b_id   bigint NOT NULL,
    CONSTRAINT relacion_tipo_relacion_check CHECK (
        (tipo_relacion)::text = ANY (ARRAY[
            'FAMILIAR','AMIGO','LABORAL','CONTACTO_TELEFONICO','REDES_SOCIALES','OTRO'
        ]::text[])
    )
);

-- --- avistamiento ----------------------------------------------------------
CREATE TABLE avistamiento (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_en    timestamp(6) without time zone,
    fecha_hora   timestamp(6) without time zone NOT NULL,
    fuente       character varying(50),
    ubicacion_id bigint NOT NULL,
    vehiculo_id  bigint NOT NULL
);

-- --- suceso_testigo (tabla puente) -----------------------------------------
CREATE TABLE suceso_testigo (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id bigint NOT NULL,
    suceso_id  bigint NOT NULL,
    CONSTRAINT uk_suceso_testigo UNIQUE (suceso_id, persona_id)
);

-- --- persona_desaparecida --------------------------------------------------
CREATE TABLE persona_desaparecida (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actualizado_en      timestamp(6) without time zone,
    alias               character varying(100),
    analisis_ia         text,
    apellido            character varying(80) NOT NULL,
    circunstancias      text,
    color_cabello       character varying(40),
    color_ojos          character varying(40),
    contextura          character varying(40),
    creado_en           timestamp(6) without time zone,
    documento           character varying(50) NOT NULL,
    estado              character varying(30) NOT NULL,
    estatura_cm         integer,
    fecha_desaparicion  timestamp(6) without time zone NOT NULL,
    fecha_nacimiento    date,
    fecha_resolucion    timestamp(6) without time zone,
    foto_url            character varying(500),
    genero              character varying(20),
    nombre              character varying(80) NOT NULL,
    peso_kg             integer,
    prioridad           character varying(20) NOT NULL,
    reportante_nombre   character varying(150),
    reportante_relacion character varying(100),
    reportante_telefono character varying(50),
    ropa_al_desaparecer text,
    senas_particulares  text,
    zonas_busqueda_ia   text,
    ultima_ubicacion_id bigint,
    CONSTRAINT uk_persona_desaparecida_documento UNIQUE (documento),
    CONSTRAINT persona_desaparecida_estado_check CHECK (
        (estado)::text = ANY (ARRAY[
            'BUSCADA','ENCONTRADA_VIVA','ENCONTRADA_FALLECIDA','ARCHIVADA'
        ]::text[])
    ),
    CONSTRAINT persona_desaparecida_prioridad_check CHECK (
        (prioridad)::text = ANY (ARRAY[
            'CRITICA','ALTA','MEDIA','BAJA'
        ]::text[])
    )
);

-- --- foto_desaparecida -----------------------------------------------------
CREATE TABLE foto_desaparecida (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_en               timestamp(6) without time zone NOT NULL,
    descripcion             character varying(255),
    orden                   integer NOT NULL,
    principal               boolean NOT NULL,
    url                     character varying(500) NOT NULL,
    persona_desaparecida_id bigint
);

-- --- alerta ----------------------------------------------------------------
CREATE TABLE alerta (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creada_en    timestamp(6) without time zone,
    descripcion  text,
    estado       character varying(20),
    nivel_riesgo character varying(10),
    tipo         character varying(40)  NOT NULL,
    titulo       character varying(150) NOT NULL,
    vinculo_id   bigint,
    CONSTRAINT alerta_estado_check CHECK (
        (estado)::text = ANY (ARRAY[
            'PENDIENTE','EN_REVISION','CONFIRMADA','DESCARTADA'
        ]::text[])
    ),
    CONSTRAINT alerta_nivel_riesgo_check CHECK (
        (nivel_riesgo)::text = ANY (ARRAY[
            'BAJO','MEDIO','ALTO','CRITICO'
        ]::text[])
    ),
    CONSTRAINT alerta_tipo_check CHECK (
        (tipo)::text = ANY (ARRAY[
            'NODO_LOGISTICO','VEHICULO_APOYO','INTERMEDIARIO','POI_DESAPARICION',
            'MODUS_OPERANDI','CLUSTER_DESAPARICIONES','DESAPARICION_NODO_SOSPECHOSO'
        ]::text[])
    )
);

-- --- vinculo ---------------------------------------------------------------
CREATE TABLE vinculo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo          boolean,
    detectado_en    timestamp(6) without time zone,
    id_destino      bigint NOT NULL,
    id_origen       bigint NOT NULL,
    regla_detectada character varying(50) NOT NULL,
    score           numeric(4,2) NOT NULL,
    tipo_destino    character varying(20) NOT NULL,
    tipo_origen     character varying(20) NOT NULL
);

-- --- modus_operandi (catalogo) ---------------------------------------------
CREATE TABLE modus_operandi (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo      boolean NOT NULL,
    codigo      character varying(60)  NOT NULL,
    descripcion character varying(400),
    etiqueta    character varying(120) NOT NULL,
    CONSTRAINT uk_modus_operandi_codigo UNIQUE (codigo)
);

-- --- patron_banda ----------------------------------------------------------
CREATE TABLE patron_banda (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          character varying(20) NOT NULL,
    descripcion     text,
    metodo_comun    character varying(100),
    primer_registro timestamp without time zone,
    ultimo_registro timestamp without time zone,
    num_sucesos     integer DEFAULT 0,
    CONSTRAINT uk_patron_banda_codigo UNIQUE (codigo)
);

-- --- configuracion_motor ---------------------------------------------------
CREATE TABLE configuracion_motor (
    id                            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_min                   integer NOT NULL,
    cluster_radio_metros          integer NOT NULL,
    cluster_radio_nodo_sospechoso integer NOT NULL,
    cluster_ventana_dias          integer NOT NULL,
    escolta_min_coincidencias     integer NOT NULL,
    escolta_ventana_minutos       integer NOT NULL,
    modus_umbral                  double precision NOT NULL,
    nodo_min_vehiculos            integer NOT NULL,
    nodo_radio_metros             integer NOT NULL,
    nodo_ventana_horas            integer NOT NULL
);

-- ============================================================================
-- 4. CLAVES FORANEAS
-- ============================================================================
ALTER TABLE vehiculo
    ADD CONSTRAINT fk_vehiculo_propietario
    FOREIGN KEY (propietario_id) REFERENCES persona(id);

ALTER TABLE suceso
    ADD CONSTRAINT fk_suceso_ubicacion
    FOREIGN KEY (ubicacion_id) REFERENCES ubicacion(id);
ALTER TABLE suceso
    ADD CONSTRAINT fk_suceso_ubicacion_ultima
    FOREIGN KEY (ubicacion_ultima_id) REFERENCES ubicacion(id);
ALTER TABLE suceso
    ADD CONSTRAINT fk_suceso_vehiculo
    FOREIGN KEY (vehiculo_id) REFERENCES vehiculo(id);
ALTER TABLE suceso
    ADD CONSTRAINT fk_suceso_victima
    FOREIGN KEY (victima_id) REFERENCES persona(id);

ALTER TABLE relacion
    ADD CONSTRAINT fk_relacion_persona_a
    FOREIGN KEY (persona_a_id) REFERENCES persona(id);
ALTER TABLE relacion
    ADD CONSTRAINT fk_relacion_persona_b
    FOREIGN KEY (persona_b_id) REFERENCES persona(id);

ALTER TABLE avistamiento
    ADD CONSTRAINT fk_avistamiento_vehiculo
    FOREIGN KEY (vehiculo_id) REFERENCES vehiculo(id);
ALTER TABLE avistamiento
    ADD CONSTRAINT fk_avistamiento_ubicacion
    FOREIGN KEY (ubicacion_id) REFERENCES ubicacion(id);

ALTER TABLE persona_desaparecida
    ADD CONSTRAINT fk_desaparecida_ubicacion
    FOREIGN KEY (ultima_ubicacion_id) REFERENCES ubicacion(id);

ALTER TABLE foto_desaparecida
    ADD CONSTRAINT fk_foto_desaparecida
    FOREIGN KEY (persona_desaparecida_id) REFERENCES persona_desaparecida(id);

-- ============================================================================
-- 5. INDICES
-- ============================================================================
CREATE INDEX idx_persona_documento     ON persona     USING btree (documento);
CREATE INDEX idx_persona_rol           ON persona     USING btree (rol);
CREATE INDEX idx_ubicacion_tipo        ON ubicacion   USING btree (tipo);
CREATE INDEX idx_vehiculo_estado       ON vehiculo    USING btree (estado);
CREATE INDEX idx_vehiculo_placa        ON vehiculo    USING btree (placa);
CREATE INDEX idx_suceso_fecha          ON suceso      USING btree (fecha_hora);
CREATE INDEX idx_suceso_modus          ON suceso      USING btree (modus_operandi);
CREATE INDEX idx_suceso_tipo           ON suceso      USING btree (tipo);
CREATE INDEX idx_relacion_a            ON relacion    USING btree (persona_a_id);
CREATE INDEX idx_relacion_b            ON relacion    USING btree (persona_b_id);
CREATE INDEX idx_avistamiento_veh_fecha ON avistamiento USING btree (vehiculo_id, fecha_hora);
CREATE INDEX idx_alerta_estado         ON alerta      USING btree (estado);
CREATE INDEX idx_alerta_tipo           ON alerta      USING btree (tipo);
CREATE INDEX idx_vinculo_destino       ON vinculo     USING btree (tipo_destino, id_destino);
CREATE INDEX idx_vinculo_origen        ON vinculo     USING btree (tipo_origen, id_origen);
CREATE INDEX idx_vinculo_regla         ON vinculo     USING btree (regla_detectada);

-- ============================================================================
-- 6. TRIGGER DE GEOMETRIA (despues de que la tabla ubicacion existe)
-- ============================================================================
DROP TRIGGER IF EXISTS tr_ubicacion_geom ON ubicacion;
CREATE TRIGGER tr_ubicacion_geom
    BEFORE INSERT OR UPDATE ON ubicacion
    FOR EACH ROW EXECUTE FUNCTION trigger_ubicacion_set_geom();

-- ============================================================================
-- 7. VISTA DEL GRAFO (etiquetas legibles de los vinculos activos)
-- ============================================================================
CREATE OR REPLACE VIEW v_grafo_vinculos AS
 SELECT id AS vinculo_id,
    tipo_origen,
    id_origen,
        CASE tipo_origen
            WHEN 'PERSONA'::text  THEN (SELECT persona.nombre || ' ' || persona.apellido FROM persona WHERE persona.id = v.id_origen)
            WHEN 'VEHICULO'::text THEN (SELECT vehiculo.placa      FROM vehiculo  WHERE vehiculo.id  = v.id_origen)::text
            WHEN 'UBICACION'::text THEN (SELECT ubicacion.direccion FROM ubicacion WHERE ubicacion.id = v.id_origen)::text
            WHEN 'SUCESO'::text   THEN ('Suceso #'::text || id_origen)
            ELSE NULL::text
        END AS label_origen,
    tipo_destino,
    id_destino,
        CASE tipo_destino
            WHEN 'PERSONA'::text  THEN (SELECT persona.nombre || ' ' || persona.apellido FROM persona WHERE persona.id = v.id_destino)
            WHEN 'VEHICULO'::text THEN (SELECT vehiculo.placa      FROM vehiculo  WHERE vehiculo.id  = v.id_destino)::text
            WHEN 'UBICACION'::text THEN (SELECT ubicacion.direccion FROM ubicacion WHERE ubicacion.id = v.id_destino)::text
            WHEN 'SUCESO'::text   THEN ('Suceso #'::text || id_destino)
            ELSE NULL::text
        END AS label_destino,
    regla_detectada,
    score,
    detectado_en
   FROM vinculo v
  WHERE activo = true;

-- ============================================================================
-- Fin del esquema. Continuar con 02-datos-ejemplo.sql para cargar datos.
-- ============================================================================
