package com.sso.users.application.usecase;

import com.sso.users.domain.model.UserStatus;
import com.sso.users.domain.port.out.EventPublisherPort;
import com.sso.users.domain.port.out.FileStoragePort;
import com.sso.users.infrastructure.adapter.out.persistence.UserJpaEntity;
import com.sso.users.infrastructure.adapter.out.persistence.UserRepository;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.UUID;

@Service
public class CreateUserService {

    private final UserRepository userRepository;
    private final FileStoragePort fileStoragePort;
    private final EventPublisherPort eventPublisherPort;

    public CreateUserService(UserRepository userRepository, FileStoragePort fileStoragePort, EventPublisherPort eventPublisherPort) {
        this.userRepository = userRepository;
        this.fileStoragePort = fileStoragePort;
        this.eventPublisherPort = eventPublisherPort;
    }

    public UserJpaEntity execute(String username, String email, String fullName, byte[] photoBytes, String photoFileName) {
        
        if (photoBytes == null || photoBytes.length == 0) {
            throw new IllegalArgumentException("La foto de perfil de cara es obligatoria.");
        }

        String photoUrl = fileStoragePort.storeFile(photoFileName, photoBytes, "image/jpeg");
        
        String autoGeneratedPassword = "{bcrypt}" + UUID.randomUUID().toString(); 

        UserJpaEntity user = UserJpaEntity.builder()
                .username(username)
                .email(email)
                .password(autoGeneratedPassword)
                .fullName(fullName)
                .profilePhotoUrl(photoUrl)
                .status(UserStatus.ACTIVE)
                .requirePasswordChange(true)
                .createdAt(Instant.now())
                .roles(new HashSet<>()) // Fetch and add ADMIN/USER roles as needed.
                .build();

        UserJpaEntity savedUser = userRepository.save(user);

        Map<String, Object> payload = new HashMap<>();
        payload.put("userId", savedUser.getId());
        payload.put("email", savedUser.getEmail());
        payload.put("tempPassword", autoGeneratedPassword);
        eventPublisherPort.publish("users-topic", "UserCreatedEvent", payload);

        return savedUser;
    }
}
