package com.nexocriminal.vehiculo.infrastructure.web;

/**
 * Autogenerated core layer for Nexo Criminal
 */
public class VehiculoController {
    // Todo: Implement business logic or ports
}

// Filter Feature Update

// Sightings Feature Update
