spring.datasource.url=postgresql://neondb_owner:npg_aGQV6E3htSZz@ep-curly-resonance-aq2rbze5-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aGQV6E3htSZz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2