package com.nexocriminal.desaparecida.infrastructure.persistence;

/**
 * Autogenerated core layer for Nexo Criminal
 */
public class UbicacionReaderAdapter {
    // Todo: Implement business logic or ports
}
