spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.threads.virtual.enabled=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.ollama.init.pull-model-strategy=when_missing

zac.mo.top-k=5
zac.mo.umbral-similitud-candidato=70.0

sso.auth.jwt-secret=${JWT_SECRET:este-es-un-secreto-de-desarrollo-cambiar-en-produccion-32chars}

server.port=8081