spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.threads.virtual.enabled=true
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.ollama.init.pull-model-strategy=when_missing

zac.mo.top-k=5
zac.mo.umbral-similitud-candidato=70.0

sso.auth.jwt-secret=${JWT_SECRET}

server.port=8081
