spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update

sso:
  auth:
    jwt-secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
