package com.nexocriminal.vehiculo.infrastructure.persistence;

/**
 * Autogenerated core layer for Nexo Criminal
 */
public class PersonaReaderAdapter {
    // Todo: Implement business logic or ports
}
