package com.nexocriminal.persona.infrastructure.persistence;

/**
 * Autogenerated core layer for Nexo Criminal
 */
public class PersonaRepositoryAdapter {
    // Todo: Implement business logic or ports
}
