package com.nexocriminal.desaparecida.infrastructure.web;

/**
 * Autogenerated core layer for Nexo Criminal
 */
public class DesaparecidaController {
    // Todo: Implement business logic or ports
}
