name: Power Ranger Red - Backend CI

on:
  push:
    paths:
      - 'teams/team-red/backend/guardia-core/**'
    branches-ignore:
      - main
  pull_request:
    paths:
      - 'teams/team-red/backend/guardia-core/**'
    branches:
      - main

jobs:
  pruebas-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Configurar Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar y Probar Módulo Ranger Red
        run: mvn clean package
        working-directory: ./teams/team-red/backend/guardia-core